C:\Users\bgazit\AppData\Local\Programs\Python\Python39\python.exe C:\Users\bgazit\PycharmProjects\Study\AppliedDeepLearning\Assignment3\task3and4.py 
	Start model 1
		Epoch 1 validation error: 0.0481, test error: 0.0487
		Epoch 2 validation error: 0.0323, test error: 0.0297
		Epoch 3 validation error: 0.0293, test error: 0.0276
		Epoch 4 validation error: 0.0268, test error: 0.0263
		Epoch 5 validation error: 0.0242, test error: 0.0229
	Start model 2
		Epoch 1 validation error: 0.0537, test error: 0.0507
		Epoch 2 validation error: 0.0346, test error: 0.0324
		Epoch 3 validation error: 0.0323, test error: 0.0318
		Epoch 4 validation error: 0.0261, test error: 0.0238
		Epoch 5 validation error: 0.0249, test error: 0.0234
	Start model 3
		Epoch 1 validation error: 0.0586, test error: 0.0503
		Epoch 2 validation error: 0.0363, test error: 0.0321
		Epoch 3 validation error: 0.0311, test error: 0.0259
		Epoch 4 validation error: 0.0285, test error: 0.024
		Epoch 5 validation error: 0.0265, test error: 0.0234
	Start model 4
		Epoch 1 validation error: 0.0511, test error: 0.0446
		Epoch 2 validation error: 0.0357, test error: 0.0341
		Epoch 3 validation error: 0.0339, test error: 0.0298
		Epoch 4 validation error: 0.0289, test error: 0.0265
		Epoch 5 validation error: 0.0245, test error: 0.0216
	Start model 5
		Epoch 1 validation error: 0.0542, test error: 0.0457
		Epoch 2 validation error: 0.0375, test error: 0.0323
		Epoch 3 validation error: 0.0313, test error: 0.0271
		Epoch 4 validation error: 0.0277, test error: 0.024
		Epoch 5 validation error: 0.0246, test error: 0.022



Min validation error found in model 1, epoch 5.
Min validation error: 0.0242.
Corresponding test error: 0.0229.

Process finished with exit code 0
